language: rust
cache: cargo

env:
  - RUSTFLAGS="-D warnings"


before_script:
  - rustup component add rustfmt

matrix:
  fast_finish: true
  include:
    - rust: stable
      os: linux
    - rust: stable
      os: osx
    #- rust: stable-x86_64-pc-windows-msvc
    #  os: windows

script:
  - cargo check --all --benches --bins --examples --tests
  - cargo test --all
  - cargo fmt --all -- --check
